#!/bin/bash
# Configure this machine's network settings for the UAV/GCS Docker
# environment. Writes .env, which is both what `docker compose` reads and
# where this script picks up its defaults on a re-run.
#
# Usage: ./setup-env.sh uav|gcs
set -e

NEW_ROLE="$1"
if [ "$NEW_ROLE" != "uav" ] && [ "$NEW_ROLE" != "gcs" ]; then
    echo "Usage: $0 uav|gcs" >&2
    echo "  Run './setup-env.sh uav' on the Raspberry Pi, './setup-env.sh gcs' on the ground station." >&2
    exit 1
fi

ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.env"

# Re-running should offer what's already configured, so source any existing
# .env for defaults. It's plain KEY=VALUE, so this is safe — but it also sets
# ROLE, so the argument is applied after this, not before.
[ -f "$ENV_FILE" ] && . "$ENV_FILE"
ROLE="$NEW_ROLE"

echo "catkin_ws network configuration (role: $ROLE)"
echo "-----------------------------------------------"
echo "Press Enter to keep the pre-filled value."
echo

read -e -i "$UAV_IP" -p "UAV IP address (Raspberry Pi): " UAV_IP
read -e -i "$GCS_IP" -p "GCS IP address (ground station): " GCS_IP
read -e -i "${VICON_SERVER_DVP:-10.68.42.85}" -p "Vicon server IP: " VICON_SERVER_DVP

if [ -z "$UAV_IP" ] || [ -z "$GCS_IP" ]; then
    echo "UAV IP and GCS IP are both required." >&2
    exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by ./setup-env.sh — re-run it to change these.
# ROLE picks the tmux launcher and ROS master default (docker/bashrc.d/).
ROLE=$ROLE
UAV_IP=$UAV_IP
GCS_IP=$GCS_IP
VICON_SERVER_DVP=$VICON_SERVER_DVP
EOF

echo
echo "Saved $ENV_FILE"
